### ISSUE TITLE
add tool to show how code is split in fragments

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart2js_info#9]
Our data model already tracks which fragment holds the generated code for a function. We should write tools to make it easy to visualize, validate, query this kind of information. For example, we want to be able to answer these kind of questions:

* what fragment did this class or function end up in?
* does my code split match my expectations of where classes and functions would go?
* why is this class not in fragment X?

The last question requires that we first fix our recording of dependency information, but in addition we might need special entries to encode deferred dependencies (so we can analyze the defer splitting rules outside of dart2js).

**Comment by sigmundch** [comment]
Here are some ideas on how to present this information to users:

**fragment identifier**

We should use a canonical descriptor that can help uniquely identify the fragment. This will be used to correlate data across different runs (compare before and after a change to the code) and to help denote fragments for validation. The descriptor might be different depending on the kind of fragment:
- the main fragment can be simply denoted by the token `main`
- fragments corresponding to a deferred import can be denoted by the import uri
- fragments that contain code shared between other fragments can use a compound list of identifiers to denote where they are expected to be loaded from.

It might be convenient to also assign numbers to each fragment to make the representation short in the output. For example:

``` sh
fragment 0: main
  ... some-details-about-main-go-here ...

fragment 1: package:foo/bar.dart
  includes also fragment 3
  ... some-details-here ...

fragment 2: package:foo/baz.dart
  includes also fragment 3
  ... some-details-here ...

fragment 3: shared by [1, 2]
  ...
```

**clustering by libraries/packages**

For the command-line tool, it will be useful to cluster information in a way that is easy to process. This might include clustering information by library or package. For example:

``` sh
fragment 0: main
  code sources:
    - package:foo
    - package:bar
    - dart:core

fragment 1: package:foo/bar.dart
  includes also fragment 3
  code sources:
    - package:baz
    - package:foo
  ...
```

**included elements**

For a command-line tool, it might be too much detail to provide all included elements in stdout, but might be possible to provide the information in a summary file-format so that it can be easily consumed elsewhere, or provide a library that makes this information easy to find (it might not be obvious by looking at dart2js_info format to see how to compute this quickly).

If we were to generate a file, it could serve as the file-format to use for validating correctness in the future. When dumping information, we would include all elements explicitly, but for a validation format we might accept glob expressions. For example, this might be a possible validation format

``` yaml
fragment:
  id: 0
  descriptor: main
  elements:
    "dart:core":
      - Uri
      - Stopwatch
      "package:foo/foo.dart":
       - myTopLevelFunction
       - A

fragment:
  id: 1
  descriptor: "package:foo/bar.dart"
  includes: [3]
  elements:
  "package:foo/bar.dart"
    - B

fragment:
  id: 2
  descriptor: "package:foo/baz.dart"
  includes: [3]
  elements:
  "package:foo/baz.dart":
    - C
    - topFoo* # elements whose name start with `topFoo`

fragment:
  id: 3
  descriptor: {shared: [1, 2]}
  elements:
  "package:foo/src/shared.dart":
    - * # all classes and top-level methods in this library
  "package:m":
    - * # all classes and top-level methods in this package
```
